In [84]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [85]:
df=pd.read_csv('data/business.csv')
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"

In [86]:
df.describe()

           num_code
count  93487.000000
mean     780.056147
std      147.616038
min      401.000000
25%      706.000000
50%      820.000000
75%      874.000000
max      996.000000

In [87]:
#feature engg process
df['Date']=df['date'].str.split('-').str[0]
df['Month']=df['date'].str.split('-').str[1]
df['Year']=df['date'].str.split('-').str[2]

In [88]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,02,2022
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,02,2022
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,02,2022
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,02,2022
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,02,2022

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  object
 12  Month       93487 non-null  object
 13  Year        93487 non-null  object
dtypes: int64(1), object(13)
memory usage: 10.0+ MB

In [90]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [91]:
df.drop('date',axis=1, inplace=True)

In [92]:
df['Price']=df['price'].str.replace(',',"")
df['Price']=df['Price'].astype(int)
df.drop('price',axis=1,inplace=True)

In [93]:
df['Arrival_hour']=df['arr_time'].str.split(':').str[0]
df['Arrival_min']=df['arr_time'].str.split(':').str[1]

In [94]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,Date,Month,Year,Price,Arrival_hour,Arrival_min
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,11,2,2022,25612,20,00
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,11,2,2022,25612,21,15

In [95]:
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_min']=df['Arrival_min'].astype(int)
df.drop('arr_time', axis=1, inplace=True)

In [96]:
df['Departure_hour']=df['dep_time'].str.split(':').str[0]
df['Departure_min']=df['dep_time'].str.split(':').str[1]

In [97]:
df['Departure_hour']=df['Departure_hour'].astype(int)
df['Departure_min']=df['Departure_min'].astype(int)
df.drop('dep_time', axis=1, inplace=True)

In [98]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,11,2,2022,25612,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,11,2,2022,25612,21,15,19,0

In [99]:
df['stop'].unique()

array(['non-stop ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '2+-stop',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t'],
      dtype=object)

In [100]:
df['Stop']=df['stop'].str.split('-').str[0]
df['Stop'].unique()

array(['non', '1', '2+'], dtype=object)

In [101]:
df['Stop']=df['Stop'].map({'non':0,'1':1,'2+':2})
df.drop('stop', axis=1,inplace=True)
df.head(3)

,airline,ch_code,num_code,from,time_taken,to,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min,Stop
0,Air India,AI,868,Delhi,02h 00m,Mumbai,11,2,2022,25612,20,0,18,0,0
1,Air India,AI,624,Delhi,02h 15m,Mumbai,11,2,2022,25612,21,15,19,0,0
2,Air India,AI,531,Delhi,24h 45m,Mumbai,11,2,2022,42220,20,45,20,0,1

In [102]:
df['hour_taken']=df['time_taken'].str.split(' ').str[0].str.split('h').str[0]
df['min_taken']=df['time_taken'].str.split(' ').str[1].str.split('m').str[0]
df.drop('time_taken',axis=1,inplace=True)

In [103]:
df['hour_taken']=df['hour_taken'].astype(int)
df['min_taken']=df['min_taken'].astype(int)

In [104]:
df['Duration(min)']=(df['hour_taken']*60)+df['min_taken']

In [105]:
df.drop(['hour_taken','min_taken'], axis=1, inplace=True)

In [106]:
df.head(2)

,airline,ch_code,num_code,from,to,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min,Stop,Duration(min)
0,Air India,AI,868,Delhi,Mumbai,11,2,2022,25612,20,0,18,0,0,120
1,Air India,AI,624,Delhi,Mumbai,11,2,2022,25612,21,15,19,0,0,135

In [107]:
df['airline'].unique()

array(['Air India', 'Vistara'], dtype=object)

In [108]:
df['from'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [109]:
df['to'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [110]:
df['ch_code'].unique()

array(['AI', 'UK'], dtype=object)

In [115]:
encoder=OneHotEncoder()
encoder.fit_transform(df[['airline','from','to','ch_code']] ).toarray()

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.]])

In [116]:
data=pd.DataFrame(encoder.fit_transform(df[['airline','from','to','ch_code']] ).toarray(),columns=encoder.get_feature_names_out())

In [122]:
f_data=pd.concat([df,data],axis=1)
f_data.head(3)
f_data.drop(['ch_code','from','to','airline'], axis=1,inplace=True)

In [123]:
f_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_code           93487 non-null  int64
 1   Date               93487 non-null  int64
 2   Month              93487 non-null  int64
 3   Year               93487 non-null  int64
 4   Price              93487 non-null  int64
 5   Arrival_hour       93487 non-null  int64
 6   Arrival_min        93487 non-null  int64
 7   Departure_hour     93487 non-null  int64
 8   Departure_min      93487 non-null  int64
 9   Stop               93487 non-null  int64
 10  Duration(min)      93487 non-null  int64
 11  airline_Air India  93487 non-null  float64
 12  airline_Vistara    93487 non-null  float64
 13  from_Bangalore     93487 non-null  float64
 14  from_Chennai       93487 non-null  float64
 15  from_Delhi         93487 non-null  float64
 16  from_Hyderabad     93487 non-null  float64
 17  from_Kolkata       93487 non-null  float64
 18  from_Mumbai        93487 non-null  float64
 19  to_Bangalore       93487 non-null  float64
 20  to_Chennai         93487 non-null  float64
 21  to_Delhi           93487 non-null  float64
 22  to_Hyderabad       93487 non-null  float64
 23  to_Kolkata         93487 non-null  float64
 24  to_Mumbai          93487 non-null  float64
 25  ch_code_AI         93487 non-null  float64
 26  ch_code_UK         93487 non-null  float64
dtypes: float64(16), int64(11)
memory usage: 19.3 MB

In [125]:
f_data.head()

,num_code,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min,Stop,...,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai,ch_code_AI,ch_code_UK
0,868,11,2,2022,25612,20,0,18,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,624,11,2,2022,25612,21,15,19,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,531,11,2,2022,42220,20,45,20,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,839,11,2,2022,44450,23,55,21,25,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,544,11,2,2022,46690,23,55,17,15,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0