In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
df=pd.read_csv('data/business.csv')
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"

In [50]:
df.describe()

           num_code
count  93487.000000
mean     780.056147
std      147.616038
min      401.000000
25%      706.000000
50%      820.000000
75%      874.000000
max      996.000000

In [51]:
#feature engg process
df['Date']=df['date'].str.split('-').str[0]
df['Month']=df['date'].str.split('-').str[1]
df['Year']=df['date'].str.split('-').str[2]

In [52]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,02,2022
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,02,2022
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,02,2022
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,02,2022
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,02,2022

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  object
 12  Month       93487 non-null  object
 13  Year        93487 non-null  object
dtypes: int64(1), object(13)
memory usage: 10.0+ MB

In [54]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [55]:
df.drop('date',axis=1, inplace=True)

In [56]:
df['Price']=df['price'].str.replace(',',"")
df['Price']=df['Price'].astype(int)
df.drop('price',axis=1,inplace=True)

In [57]:
df['Arrival_hour']=df['arr_time'].str.split(':').str[0]
df['Arrival_min']=df['arr_time'].str.split(':').str[1]

In [58]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,Date,Month,Year,Price,Arrival_hour,Arrival_min
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,11,2,2022,25612,20,00
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,11,2,2022,25612,21,15

In [59]:
df['Arrival_hour']=df['Arrival_hour'].astype(int)
df['Arrival_min']=df['Arrival_min'].astype(int)
df.drop('arr_time', axis=1, inplace=True)

In [60]:
df['Departure_hour']=df['dep_time'].str.split(':').str[0]
df['Departure_min']=df['dep_time'].str.split(':').str[1]

In [61]:
df['Departure_hour']=df['Departure_hour'].astype(int)
df['Departure_min']=df['Departure_min'].astype(int)
df.drop('dep_time', axis=1, inplace=True)

In [62]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,11,2,2022,25612,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,11,2,2022,25612,21,15,19,0

In [63]:
df['stop'].unique()

array(['non-stop ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '2+-stop',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t'],
      dtype=object)

In [64]:
df['Stop']=df['stop'].str.split('-').str[0]
df['Stop'].unique()

array(['non', '1', '2+'], dtype=object)

In [65]:
df['Stop']=df['Stop'].map({'non':0,'1':1,'2+':2})
df.drop('stop', axis=1,inplace=True)
df.head(3)

,airline,ch_code,num_code,from,time_taken,to,Date,Month,Year,Price,Arrival_hour,Arrival_min,Departure_hour,Departure_min,Stop
0,Air India,AI,868,Delhi,02h 00m,Mumbai,11,2,2022,25612,20,0,18,0,0
1,Air India,AI,624,Delhi,02h 15m,Mumbai,11,2,2022,25612,21,15,19,0,0
2,Air India,AI,531,Delhi,24h 45m,Mumbai,11,2,2022,42220,20,45,20,0,1

In [67]:
df['time_taken'].str.split(' ').str[0].str.split('h').str[0]

0        02
1        02
2        24
3        26
4        06
         ..
93482    10
93483    10
93484    13
93485    10
93486    10
Name: time_taken, Length: 93487, dtype: object