In [63]:
import pandas as pd

In [64]:
data=[1,2,3,4,5]
ser=pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [65]:
#Create a series from dictionary
dict={'a':1,'b':2,'c':3}
series=pd.Series(dict)
print(series)

a    1
b    2
c    3
dtype: int64

In [66]:
index=['A','B','C','D','E']
seri=pd.Series(data,index=index)
print(seri)

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [67]:
data={
    'Name':['Abhi','Jhon','Krish'],
    'Age':[23,33,26],
    'City':['Punjab','USA','Russia']
}
df=pd.DataFrame(data)
print(df)

    Name  Age    City
0   Abhi   23  Punjab
1   Jhon   33     USA
2  Krish   26  Russia

In [68]:
import numpy as np
np.array(df)

array([['Abhi', 23, 'Punjab'],
       ['Jhon', 33, 'USA'],
       ['Krish', 26, 'Russia']], dtype=object)

In [69]:
#create a dataframe from the list of dictionaries
data=[
    {'Name':'Abhishek','Age':22,'City':'Phagwara'},
    {'Name':'Karan','Age':25,'City':'Ludhiana'},
    {'Name':'Vivek','Age':21,'City':'jalandhar'},
    {'Name':'Aastha','Age':23,'City':'Mohali'},
    {'Name':'Aman','Age':25,'City':'Bihar'}
]
df=pd.DataFrame(data)
print(df)

       Name  Age       City
0  Abhishek   22   Phagwara
1     Karan   25   Ludhiana
2     Vivek   21  jalandhar
3    Aastha   23     Mohali
4      Aman   25      Bihar

In [70]:
df.loc[0:3]

       Name  Age       City
0  Abhishek   22   Phagwara
1     Karan   25   Ludhiana
2     Vivek   21  jalandhar
3    Aastha   23     Mohali

In [71]:
df.iloc[1][0]

C:\Users\HP\AppData\Local\Temp\ipykernel_24888\1019881219.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][0]

'Karan'

In [72]:
df.at[0,'Name']

'Abhishek'

In [73]:
df.iat[4,2]

'Bihar'

In [74]:
#Manipulation
df['Salary']=[12000,15000,14000,np.nan,np.nan]
print(df)

       Name  Age       City   Salary
0  Abhishek   22   Phagwara  12000.0
1     Karan   25   Ludhiana  15000.0
2     Vivek   21  jalandhar  14000.0
3    Aastha   23     Mohali      NaN
4      Aman   25      Bihar      NaN

In [75]:
df.drop('Salary', axis=1)

       Name  Age       City
0  Abhishek   22   Phagwara
1     Karan   25   Ludhiana
2     Vivek   21  jalandhar
3    Aastha   23     Mohali
4      Aman   25      Bihar

###### axis =0   RoW         By Default

###### axis =1   Column

In [76]:
df   #drop is not a permanent, for that you have to pass inplace=True

       Name  Age       City   Salary
0  Abhishek   22   Phagwara  12000.0
1     Karan   25   Ludhiana  15000.0
2     Vivek   21  jalandhar  14000.0
3    Aastha   23     Mohali      NaN
4      Aman   25      Bihar      NaN

In [77]:
df.drop('Salary', axis=1, inplace=True)

In [78]:
df

       Name  Age       City
0  Abhishek   22   Phagwara
1     Karan   25   Ludhiana
2     Vivek   21  jalandhar
3    Aastha   23     Mohali
4      Aman   25      Bihar

In [79]:
df['Age']=df['Age']+1
df

       Name  Age       City
0  Abhishek   23   Phagwara
1     Karan   26   Ludhiana
2     Vivek   22  jalandhar
3    Aastha   24     Mohali
4      Aman   26      Bihar

In [80]:
df.drop([3],inplace=True)
df

       Name  Age       City
0  Abhishek   23   Phagwara
1     Karan   26   Ludhiana
2     Vivek   22  jalandhar
4      Aman   26      Bihar

In [81]:
df=pd.read_csv('data/results.csv')

In [82]:
type(df)

pandas.core.frame.DataFrame

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   Hindi       1000 non-null   int64
 2   English     1000 non-null   int64
 3   Science     1000 non-null   int64
 4   Maths       1000 non-null   int64
 5   History     1000 non-null   int64
 6   Geograpgy   1000 non-null   int64
 7   Total       1000 non-null   int64
 8   Results     1000 non-null   int64
 9   Div         1000 non-null   int64
dtypes: int64(10)
memory usage: 78.2 KB

In [84]:
df.describe()

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,51.645000,50.110000,49.440000,49.553000,49.03400,50.028000,299.810000,0.350000,1.856000
std,288.819436,29.471912,28.048505,28.921114,28.632447,28.76975,28.710268,71.865239,0.477208,0.904479
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,103.000000,0.000000,0.000000
25%,249.750000,26.000000,26.000000,25.000000,25.750000,24.00000,26.000000,254.000000,0.000000,1.000000
50%,499.500000,53.000000,50.500000,50.000000,49.000000,49.00000,49.000000,296.000000,0.000000,2.000000
75%,749.250000,77.000000,75.000000,73.250000,74.000000,73.25000,75.000000,349.250000,1.000000,3.000000
max,999.000000,99.000000,99.000000,99.000000,99.000000,99.00000,99.000000,505.000000,1.000000,3.000000

In [85]:
df.columns

Index(['Unnamed: 0', 'Hindi', 'English', 'Science', 'Maths', 'History',
       'Geograpgy', 'Total', 'Results', 'Div'],
      dtype='object')

In [86]:
df.shape

(1000, 10)

In [87]:
df

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1
4,4,39,81,37,38,6,54,255,1,3
...,...,...,...,...,...,...,...,...,...,...
995,995,55,89,68,58,13,13,296,0,2
996,996,42,62,25,87,51,68,335,1,2
997,997,9,83,70,14,11,78,265,0,3
998,998,23,82,31,42,84,52,314,0,2
999,999,75,78,68,33,79,91,424,1,1

In [88]:
#pandas format is similar to dictionary of lists
df['Div']

0      3
1      1
2      2
3      1
4      3
      ..
995    2
996    2
997    3
998    2
999    1
Name: Div, Length: 1000, dtype: int64

In [89]:
type(df['Div'])

pandas.core.series.Series

In [90]:
df['Div'][3]

np.int64(1)

In [91]:
df.at[43 ,'Science']

np.int64(24)

In [92]:
#Same as df['Science']
df.Science

0      59
1       4
2      76
3      59
4      37
       ..
995    68
996    25
997    70
998    31
999    68
Name: Science, Length: 1000, dtype: int64

In [93]:
Total=df[['Total','Div']]
Total

     Total  Div
0      245    3
1      362    1
2      352    2
3      377    1
4      255    3
..     ...  ...
995    296    2
996    335    2
997    265    3
998    314    2
999    424    1

[1000 rows x 2 columns]

In [94]:
total_copy=Total.copy()

In [95]:
df.loc[243]       #Row wise

Unnamed: 0    243
Hindi           3
English        35
Science        38
Maths          49
History        62
Geograpgy      83
Total         270
Results         1
Div             0
Name: 243, dtype: int64

In [96]:
df.head(4)

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1

In [97]:
df.at[0,'Total']

np.int64(245)

In [98]:
df.Total.first_valid_index()

0

In [99]:
df.loc[108:115]

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
108,108,57,60,7,63,95,40,322,1,2
109,109,55,19,23,47,33,20,197,0,0
110,110,13,20,82,61,91,34,301,0,2
111,111,52,82,79,47,6,98,364,1,1
112,112,61,53,90,7,94,89,394,1,1
113,113,76,76,94,36,1,73,356,1,2
114,114,38,25,10,14,34,84,205,0,3
115,115,84,22,5,57,83,80,331,0,2

In [100]:
df.sample(10)

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
278,278,68,34,55,38,77,39,311,1,2
498,498,62,82,54,70,48,33,349,1,2
670,670,99,90,81,60,83,50,463,1,1
518,518,97,20,12,32,84,62,307,0,2
631,631,39,1,17,74,10,5,146,0,0
773,773,7,23,27,45,50,6,158,0,0
808,808,13,77,95,61,65,96,407,1,1
678,678,66,22,45,36,32,45,246,0,3
830,830,16,76,69,17,15,67,260,0,3
979,979,12,79,13,28,1,4,137,0,0