In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('data/Details.csv')
df.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [4]:
df.tail(5)

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

In [5]:
df.shape

(1500, 7)

In [6]:
df.describe()

            Amount      Profit     Quantity
count  1500.000000  1500.00000  1500.000000
mean    291.847333    24.64200     3.743333
std     461.924620   168.55881     2.184942
min       4.000000 -1981.00000     1.000000
25%      47.750000   -12.00000     2.000000
50%     122.000000     8.00000     3.000000
75%     326.250000    38.00000     5.000000
max    5729.000000  1864.00000    14.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

In [8]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object

In [9]:
#Handling missing values
df.isnull().any()

Order ID        False
Amount          False
Profit          False
Quantity        False
Category        False
Sub-Category    False
PaymentMode     False
dtype: bool

In [10]:
df.isna().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [11]:
df_filled=df.fillna(0)

In [12]:
#filling missing value with the mean of the column
df['Profit_fill']=df['Profit'].fillna(df['Profit'].mean())

In [13]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Profit_fill
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,658
1,B-26055,5729,64,14,Furniture,Chairs,EMI,64
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,146
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,712
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,1151
...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD,-3
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI,-35
1497,B-25973,4141,1698,13,Electronics,Printers,COD,1698
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD,-2
1499,B-25993,4363,305,5,Furniture,Tables,EMI,305

In [14]:
df.dtypes

Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
Profit_fill      int64
dtype: object

In [15]:
#Renaming Columns
df=df.rename(columns={'PaymentMode': 'Payment'})
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,Payment,Profit_fill
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,658
1,B-26055,5729,64,14,Furniture,Chairs,EMI,64
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,146
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,712
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,1151
...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD,-3
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI,-35
1497,B-25973,4141,1698,13,Electronics,Printers,COD,1698
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD,-2
1499,B-25993,4363,305,5,Furniture,Tables,EMI,305

In [16]:
#change Datatype
df['value_new']=df['Quantity'].astype(float)
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,Payment,Profit_fill,value_new
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,658,7.0
1,B-26055,5729,64,14,Furniture,Chairs,EMI,64,14.0
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,146,8.0
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,712,8.0
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,1151,4.0
...,...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD,-3,2.0
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI,-35,7.0
1497,B-25973,4141,1698,13,Electronics,Printers,COD,1698,13.0
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD,-2,1.0
1499,B-25993,4363,305,5,Furniture,Tables,EMI,305,5.0

In [17]:
df['New Value']=df['Quantity'].apply(lambda x:x*2)
df.head(4)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,Payment,Profit_fill,value_new,New Value
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,658,7.0,14
1,B-26055,5729,64,14,Furniture,Chairs,EMI,64,14.0,28
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,146,8.0,16
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,712,8.0,16

In [19]:
#Data Aggredating and Grouping
grouped_mean=df.groupby('Category')['Profit'].mean()
grouped_mean

Category
Clothing       14.041096
Electronics    42.733766
Furniture      43.111111
Name: Profit, dtype: float64

In [20]:
df.groupby(['Category','Payment'])['Profit'].mean()

Category     Payment
Clothing     COD             12.804933
             Credit Card     27.483146
             Debit Card       9.953125
             EMI             24.446154
             UPI             10.429864
Electronics  COD             40.789062
             Credit Card    103.512195
             Debit Card      43.553191
             EMI             39.323529
             UPI              5.396552
Furniture    COD             14.681818
             Credit Card    179.454545
             Debit Card      13.814815
             EMI             90.380952
             UPI             12.846154
Name: Profit, dtype: float64

In [22]:
#aggregate multiple function  
grouped_agg=df.groupby('Category')['Profit'].agg(['mean','sum','count'])
grouped_agg

                  mean    sum  count
Category
Clothing     14.041096  13325    949
Electronics  42.733766  13162    308
Furniture    43.111111  10476    243

In [35]:
#Merging and Joining DataFrames
df1=pd.DataFrame({'key':['A','B','C'],'value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'value2':[4,5,6]})

In [36]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [37]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [38]:
pd.merge(df1,df2,on="key",how="inner")

  key  value1  value2
0   A       1       4
1   B       2       5

In [40]:
pd.merge(df1,df2,on="key",how="outer")

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [41]:
pd.merge(df1,df2,on="key",how="left")

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [42]:
pd.merge(df1,df2,on="key",how="right")

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6